name: Miscellaneous
description: For issues that don't belong in other categories
labels: ["type: misc", "needs-triage"]
body:
-   type: markdown
    attributes:
        value: |
            Thanks for helping PyScript be amazing. We are nothing without people like you helping build a better community 💐!

-   type: checkboxes
    id: checks
    attributes:
        label: Checklist
        description: Please confirm and check all the following options.
        options:
        -   label: I added a descriptive title
            required: true
        -   label: I searched for other issues and couldn't find a duplication
            required: true
-   type: textarea
    id: what
    attributes:
        label: What is the issue/comment/problem?
        description: This is a miscellaneous issue so this could be just about anything. We simply ask that you provide as many details as you can to help spur discussion or the outcome you want.
    validations:
        required: true
